  before_install: 
    - "cd \"01 FaceDetection\""
  language: csharp
  solution: FaceDetection.sln
  
#Project02: 
#  compiler: 
#    - clang
#    - gcc
#  language: cpp
#  script: 
#    - "cd \"02 hevc\"\\build\\linux"
#   - "mkdir build"
#    - "cd build"
#    - "cmake .. && make"


#language: csharp
#mono:
#  - latest
#before_install:
#  - cd "03 Codek Tester"
#solution: "CodekTester.sln"

#after_failure:
#  - ls -LR 
